### ISSUE TITLE
TVS-Diodes are wrong orientation

### ISSUE THREAD

**Issue by JulianBonk** [gkasprow/IoTaWatt_DIN#1]
Hi i just build one of your IotaWatts. When i tried to connect 3v3 from an external power supply the board draws >1A and the voltage breaks down to ~1V.

The issue seems to be, that the TVS diodes you added (D1, D2, D3, D4) are oriented in the wrong way. The central diode goes from P3V3 to GND :
![image](https://github.com/gkasprow/IoTaWatt_DIN/assets/58124461/49d9cfdd-4f30-4354-962c-7b3d877a0ea9)

but the Datasheet (https://assets.nexperia.com/documents/data-sheet/PRTR5V0U4D.pdf) shows it the other way around:
![image](https://github.com/gkasprow/IoTaWatt_DIN/assets/58124461/63b22b44-99be-4f53-960e-2863121e6ff2)

**Comment by gkasprow** [comment]
You are right. I've just received pcbs but didn't mount them yet.

**Comment by gkasprow** [comment]
Just rotate them by 180 degrees

**Comment by gkasprow** [comment]
@JulianBonk  what is the progress? Did you make it running ?

**Comment by JulianBonk** [comment]
I rotated them and now everything works as expected 👍
